include $(SRC_RT)/myOS/kernel/mem/Makefile

KERNEL_OBJS = output/myOS/kernel/tick.o \
	      output/myOS/kernel/wallClock.o \
		  output/myOS/kernel/task.o \
		  output/myOS/kernel/task_SJF.o \
		  output/myOS/kernel/task_Priority.o\
	      $(MEM_OBJS)
